#!/bin/bash
#SBATCH --job-name=tiger_inf_beauty
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --time=2:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --output=logs/tiger_inf_%j.out
#SBATCH --error=logs/tiger_inf_%j.err

module purge
module load 2025
module load Anaconda3/2025.06-1

source $(conda info --base)/etc/profile.d/conda.sh
conda activate RecSys

export OMP_NUM_THREADS=8

cd $HOME/GRID

BASE=/projects/prjs2120/groups/group_08
  

python -m src.inference experiment=tiger_inference_flat \
    data_dir=$BASE/data/amazon_data/beauty \ 
    semantic_id_path=$BASE/results/sid/beauty_v2/rkmeans_inference/pickle/merged_predictions_tensor.pt \
    ckpt_path=$BASE/results/tiger/beauty_rkmeans/checkpoints/checkpoint_epoch=000_step=004500.ckpt \ # this can be found in the log dir for training GR models
    num_hierarchies=4 \
    hydra.run.dir=$BASE/results/tiger/beauty_rkmeans/inference \



