#!/bin/bash
#SBATCH --job-name=tiger_train_sports
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --time=10:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --output=logs/tiger_train_%j.out
#SBATCH --error=logs/tiger_train_%j.err

module purge
module load 2025
module load Anaconda3/2025.06-1

source $(conda info --base)/etc/profile.d/conda.sh
conda activate RecSys

export OMP_NUM_THREADS=8

cd $HOME/GRID

BASE=/projects/prjs2120/groups/group_08
BASE_SCRATCH=/scratch-shared/$USER

python -m src.train experiment=tiger_train_flat \
    data_dir=$BASE/data/amazon_data/sports \
    semantic_id_path=$BASE/results/sid_rkmeans/sports/rkmeans_inference/pickle/merged_predictions_tensor.pt \
    num_hierarchies=4 \
    hydra.run.dir=$BASE_SCRATCH/results/tiger_default_2/sports_rkmeans