#!/bin/bash
#SBATCH --job-name=train_sids_beauty
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err

module purge
module load 2025
module load Anaconda3/2025.06-1

source $(conda info --base)/etc/profile.d/conda.sh
conda activate RecSys

cd $HOME/GRID

export OMP_NUM_THREADS=8

BASE=/projects/prjs2120/groups/group_08

python -m src.train experiment=rkmeans_train_flat \
    data_dir=$BASE/data/amazon_data/beauty \
    embedding_path=$BASE/results/embeddings/beauty_v2/pickle/merged_predictions_tensor.pt \
    embedding_dim=2048 \
    num_hierarchies=3 \
    codebook_width=256 \
    hydra.run.dir=$BASE/results/sid_rkmeans/beauty/rkmeans_train

